name: Deploy on tag
on:
  push:
    tags:
    - '*'
jobs:
  build-and-deploy:
    runs-on: linux
    steps:
    - name: Checkout
      if: github.ref == 'refs/heads/main'
      uses: actions/checkout@v2
